### ISSUE TITLE
When editing webhook filters there are no doc on how to change page

### ISSUE THREAD

**Issue by IsakWahl** [trello-talk/tacobot.app#15]
Im sorry that I created this as an issue, but I have tried some many commands and nothing works. So I figured this is the best place to post. Does anyone know which command this is when using T!editwebhook ID filters ?

**Comment by Snazzah** [comment]
You can allow page changes by giving the bot `Add Reactions` permissions.
Next time, ask these questions in the support server @ https://tacobot.app/server
